#include <QString>
#include <QWidget>

void ItemNotExistMsg();
void LogOutMsg();
void AddItemEmptyMsg();
void DBFailMsg();
void ItemExistMsg();
void AddItemSuccessfullyMsg();
void EditItemSuccessfullyMsg();
void AddEmployeeMsg();
void CantDiscountMsg();
void AddBillExpireMsg();
void AddBillSuccessfullyMsg();
void EditBillSuccessfullyMsg();
void ReadBillFailedMsg();
void NotEnoughAmountMsg();
void AmountOverFlowMsg();
void ClientNameNotVaildMsg();
void CartIdNotExistMsg();
void ItemNotExistOnCartIDMsg(QString);
void ClientHasNoBillLeft();
void ClientFinishPaymentMsg();
void ClientBillAboveTotalPriceMsg();
void SupplierNotExist();
void AddShotItemSuccessfully();
void AddExpensesSuccessfully();
void CobonGraterTotal();
void PaidGraterCash();
bool YesNoMsg(QString);
void ConfigUpdated();
